export const ADD_AUTH = 'AUTH.ADD_AUTH'

export const LOGOUT_AUTH = 'AUTH.LOGOUT_AUTH'

export const REQUESTING_AUTH = 'AUTH.REQUESTING_AUTH'

export const REQUESTING_AUTH_FINISHED = 'AUTH.REQUESTING_AUTH_FINISHED'

export const ADD_TOAST = 'TOASTSACTION.ADD_TOAST'

export const REMOVE_TOAST = 'TOASTSACTION.REMOVE_TOAST'
